apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-project-deployment
spec:
  selector:
    matchLabels:
      app: group-project
  replicas: 1
  template:
    metadata:
      labels:
        app: group-project
    spec:
      containers:
        - name: group-project
          image: group-project
          imagePullPolicy: Never
          ports:
            - containerPort: 9090